### ISSUE TITLE
Message 'Not Implemented'

### ISSUE THREAD

**Issue by DonRichards** [gdcc/python-dvuploader#7]
Not sure what [this](https://gist.github.com/DonRichards/5d3e160ff0d1fb3b4effcf17d7c45d0f) error indicates.

I'm trying to upload FITS files to a DOI. I can use the UI and it uploads without an issue.

- config.yml
```yml
persistent_id: doi:10.7281/T1/HSYYY0
dataverse_url: https://dataverse-test.jhu.edu
api_token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
files:
- filepath: /mnt/FitsFiles/Platinu_1005323342868820864.fits
  mimetype: image/fits
  description: Posterior distributions of the stellar parameters for the star with
    ID from the Gaia catalog Platinu_1005323342868820864.
- filepath: /mnt/FitsFiles/Platinu_1006486484435386496.fits
  mimetype: image/fits
  description: Posterior distributions of the stellar parameters for the star with
    ID from the Gaia catalog Platinu_1006486484435386496.
```
I'm not sure if this is a problem with the uploader, the way I'm upload, the dataset in general, etc. Apologies if this turns out not to be associated with the python dvuploader. I assume it does since I can use the UI for the same files.
